CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description  VARCHAR(1000)                           NOT NULL,
    requestor_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL PRIMARY KEY,
    name         VARCHAR(50)                                    NOT NULL,
    description  VARCHAR(1000)                                  NOT NULL,
    is_available BOOLEAN,
    owner_id     BIGINT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    request_id   BIGINT REFERENCES item_requests (id) ON DELETE CASCADE
);
