CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255) NOT NULL,
    email   VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user_id PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description  VARCHAR(1000) NOT NULL,
    requestor_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(50)   NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    is_available BOOLEAN,
    owner_id     BIGINT        NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    request_id   BIGINT        REFERENCES item_requests (id) ON DELETE SET NULL,
    CONSTRAINT pk_item_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id      BIGINT                      NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    requestor_id BIGINT                      NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    request_id   BIGINT                      REFERENCES item_requests (id) ON DELETE SET NULL,
    status       VARCHAR(15)                 NOT NULL,
    CONSTRAINT pk_booking_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text          varchar(1000)               NOT NULL,
    commentAuthor BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    item          BIGINT REFERENCES items (id) ON DELETE CASCADE,
    time_created  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment_id PRIMARY KEY (id)
);
